# Generated by Django 4.1 on 2023-03-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionnality',
            options={'verbose_name_plural': 'functionnalities'},
        ),
    ]
